### PR TITLE
Update HockeyApp IOS SDK to 3.8.5

### PR DESCRIPTION
**Pull request by ryuyu**
Also removes the bitcode warnings as this version of the sdk supports bitcode.

@dlevine82 @Chuxel @lostintangent

### CODE REVIEW

**Comment by lostintangent** [comment]
LGTM!

**Comment by Chuxel** [comment]
I take it we got confirmation that its fixed in the SDK, if so great!  

So did you upgrade the SDK?  If so, did you also make sure the symlinks are blown out to files in the plugin?  (I can't tell very well from the PR.)

**Comment by Chuxel** [comment]
BTW - An alternate solution here that would prevent you from having to blow out the contents of the symlinks under sub-folders would be to add a hook with my symlink reconstruction code in it.  This is what Sergey did in a PR to the Facebook Connect plugin.  That can help on Windows with the max path limit.  See https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1022

**Comment by ryuyu** [comment]
Looks like when i unzipped the SDK on linux, it filled in the symlinks for me, so this is taken care of already. Thanks Chuck!

**Pull request merged**
